### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Taskeren** [Taskeren/mineQuery-1.17#2]
```
---- Minecraft Crash Report ----
// Who set us up the TNT? 

Time: 2021/7/5 上午6:24
Description: Initializing game

 java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'minequery'!
         at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
         at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
         at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
         at net.minecraft.class_310.redirect$zne000$catchFabricInit(class_310.java:7564)
         at net.minecraft.class_310.(class_310.java:459)
         at net.minecraft.client.main.Main.main(Main.java:179)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
         at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
         at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
         at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/state/property/Property
         at cn.taskeren.minequery.MineQueryMod.onInitializeClient(MineQueryMod.java:29)
         at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
         ... 12 more Caused by: java.lang.ClassNotFoundException: net.minecraft.state.property.Property
         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
         at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
         ... 14 more

 A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread Stacktrace:
         at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
         at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)

-- Initialization --
Details: Stacktrace:
         at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:38)
         at net.minecraft.class_310.redirect$zne000$catchFabricInit(class_310.java:7566)
         at net.minecraft.class_310.(class_310.java:459)
         at net.minecraft.client.main.Main.main(Main.java:179)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
         at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
         at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
         at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
         Minecraft Version: 1.17
         Minecraft Version ID: 1.17
         Operating System: Windows 10 (amd64) version 10.0
         Java Version: 16.0.1, Oracle Corporation
         Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
         Memory: 429025280 bytes (409 MiB) / 816840704 bytes (779 MiB) up to 1050673152 bytes (1002 MiB)
         CPUs: 2
         Processor Vendor: GenuineIntel
         Processor Name: Intel(R) Celeron(R) CPU G3900 @ 2.80GHz
         Identifier: Intel64 Family 6 Model 94 Stepping 3
         Microarchitecture: Skylake (Client)
         Frequency (GHz): 2.81
         Number of physical packages: 1
         Number of physical CPUs: 2
         Number of logical CPUs: 2
         Graphics card #0 name: Intel(R) HD Graphics 510
         Graphics card #0 vendor: Intel Corporation (0x8086)
         Graphics card #0 VRAM (MB): 1024.00
         Graphics card #0 deviceId: 0x1902
         Graphics card #0 versionInfo: DriverVersion=25.20.100.6472
         Memory slot #0 capacity (MB): 4096.00
         Memory slot #0 clockSpeed (GHz): 2.40
         Memory slot #0 type: DDR4
         Virtual memory max (MB): 10635.75
         Virtual memory used (MB): 4192.27
         Swap memory total (MB): 6632.00
         Swap memory used (MB): 180.75
         JVM Flags: 1 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
         Fabric Mods:
                  architectury: Architectury 2.0.14
                 betterf3: BetterF3 1.1.5
                 chunkpregen: Fabric Chunk Pregenerator 0.3.3
                 cloth-basic-math: Cloth Basic Math 0.5.1
                 cloth-config2: Cloth Config v4 5.0.34
                 fabric: Fabric API 0.36.0+1.17
                 fabric-api-base: Fabric API Base 0.3.0+a02b44633d
                 fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
                 fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
                 fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
                 fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
                 fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
                 fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
                 fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
                 fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
                 fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
                 fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
                 fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
                 fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
                 fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
                 fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
                 fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
                 fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
                 fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
                 fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
                 fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
                 fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
                 fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
                 fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
                 fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
                 fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
                 fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
                 fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
                 fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
                 fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
                 fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
                 fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
                 fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
                 fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
                 fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
                 fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
                 fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
                 fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
                 fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
                 fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
                 fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
                 fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
                 fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
                 fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
                 fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
                 fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
                 fabricloader: Fabric Loader 0.11.6
                 inventoryhud: Inventory HUD + 3.3.2
                 inventoryprofilesnext: Inventory Profiles 0.7.4
                 java: OpenJDK 64-Bit Server VM 16
                 lightoverlay: Light Overlay 6.0.0
                 litematica: Litematica 0.0.0-dev.20210616.033538
                 lithium: Lithium 0.7.2
                 malilib: MaLiLib 0.10.0+dev.22
                 minecraft: Minecraft 1.17
                 minequery: MineQuery 1.2.0
                 mm: Manningham Mills 2.2
                 modmenu: Mod Menu 2.0.2
                 notenoughcrashes: Not Enough Crashes 3.3.1+1.17
                 org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
                 org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
                 org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
                 org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
                 org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
                 org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
                 org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
                 org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
                 randomtitle: RandomTitle 1.7
                 roughlyenoughitems: Roughly Enough Items 6.0.258-alpha
                 shulkerboxtooltip: Shulker Box Tooltip 3.0.0-alpha.4+1.17
                 spark: spark ${pluginVersion}
                 starlight: Starlight fabric-1.0.0-RC2-3a77ed1
                 tweakeroo: Tweakeroo 0.10.0-dev.20210614.173711
                 wi_zoom: WI Zoom 1.3-MC1.17
                 wthit: wthit 3.6.1
                 xaerobetterpvp: Better PVP Mod 21.11.5
         Launched Version: 1.17
         Backend library: LWJGL version 3.2.2 build 10
         Backend API: NO CONTEXT
         Window size:
         GL Caps: Using framebuffer using OpenGL 3.2
         GL debug messages:
         Using VBOs: Yes
         Is Modded: Definitely; Client brand changed to 'fabric'
         Type: Client (map_client.txt)
         CPU:
         Suspected Mods: MineQuery (minequery)
```

**Comment by Taskeren** [comment]
已解决，似乎是使用了开发jar。
